targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            sound_library: lib/library/persistence/library_database.dart
          schema_dir: drift_schemas/
          test_dir: test/generated_migrations/
